#!/bin/bash

# Miner installer: this will install dependencies, drivers and miner service
# Corporation: Versates INC
# Author: Inacio Klassmann

set -e

RIG_ID=$(hostname)
COIN=eth
USER=versates
GPU_DRIVER_NAME="amdgpu-pro-17.10-414273"
URL_FILES=https://bitbucket.org/versahub/mining-files/raw/master

if [ "$1" != "" ]; then
  COIN=$1
fi

if [ ! -f "wallets/$COIN-wallet" ]; then
  echo "There is no WALLET for $COIN coin!"
  exit 2
fi

if [ ! -f "miners/install-$COIN-miner" ]; then
  echo "There is no INSTALLER for $COIN coin!"
  exit 3
fi

./install-dependencies $URL_FILES

# install GPU driver
echo "##############   INSTALLING AMD GPU DRIVER   ##############"
if [ ! -f $GPU_DRIVER_NAME.tar.xz ]; then
    wget $URL_FILES/$GPU_DRIVER_NAME.tar.xz
fi
tar -Jxvf $GPU_DRIVER_NAME.tar.xz
$GPU_DRIVER_NAME/amdgpu-pro-install -y
usermod -a -G video $USER
rm -rf $GPU_DRIVER_NAME

echo "Installing $COIN miner..."
./miners/install-$COIN-miner $URL_FILES $RIG_ID radeon

echo "PLEASE REBOOT YOUR SYSTEM!"

exit 1

