#!/bin/bash

# Change hostname
# Corporation: Versates INC
# Author: Inacio Klassmann

set -e

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <HOSTNAME>" >&2
  exit 1
fi

OLD_HOSTNAME="$( hostname )"
NEW_HOSTNAME="$1"

echo "Changing hostname from $OLD_HOSTNAME to $NEW_HOSTNAME..."

hostname "$NEW_HOSTNAME"
sed -i "s/$OLD_HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts
sed -i "s/$OLD_HOSTNAME/$NEW_HOSTNAME/g" /etc/hostname

exit 1